/* Fixup */
SYSCALL_ARGC(__NR_lookup_dcookie, 3)
SYSCALL_ARGC(__NR_vhangup, 0)
SYSCALL_ARGC(__NR_sync, 0)
SYSCALL_ARGC(__NR_sched_yield, 0)
SYSCALL_ARGC(__NR_restart_syscall, 0)
SYSCALL_ARGC(__NR_setsid, 0)
SYSCALL_ARGC(__NR_getpid, 0)
SYSCALL_ARGC(__NR_getppid, 0)
SYSCALL_ARGC(__NR_getuid, 0)
SYSCALL_ARGC(__NR_geteuid, 0)
SYSCALL_ARGC(__NR_getgid, 0)
SYSCALL_ARGC(__NR_getegid, 0)
SYSCALL_ARGC(__NR_gettid, 0)
